### ISSUE TITLE
No "tsutils" dependency

### ISSUE THREAD

**Issue by michalstocki** [vladimiry/tslint-rules-bunch#1]
When I'm trying to use this plugin, the following error occurs:
```
TypeError: tsutils_1.findImports is not a function
    at walk (node_modules/tslint-rules-bunch/rules/noImportZonesRule.js:93:37)
```

After a quick investigation I found that you make use of `tsutils` library (https://github.com/vladimiry/tslint-rules-bunch/blob/master/src/lib/rules/noImportZonesRule.ts#L7) , but there is no `tsutils` in `"dependencies"` section of `package.json`.

**Comment by vladimiry** [comment]
`tsutils` is a dependency of `tslint` https://github.com/palantir/tslint/blob/master/package.json#L51 so it's supposed to work well having the `tslint` installed.

But I agree it's better to list the used dependencies explicitly, going to do that.

**Comment by michalstocki** [comment]
I have tslint installed (of course) but it didn't worked for me. I installed dependencies via Yarn. Maybe this makes the difference…

**Comment by vladimiry** [comment]
PR of adding `tsutils` as an explicit dependency is appreciated, as I won't be able to do that earlier than in a few days.

**Comment by vladimiry** [comment]
`tsutils` module has been added as an explicit dependency.
